### PR TITLE
Add Sketch Measure JSON import JSON support.

### PR DESCRIPTION
**Pull request by griffin-stewie**
This export supports JSON for Sketch Measure’s import format.

I'm using Prism for managing Colors and using Sketch Measure to share design specs for developers. When I see spec html exported by Sketch Measure, Color names which Prism named aren't there. To solve this problem, Sketch Measure shows us color name if we use Sketch Measures' "Named Color" feature and it supports importing JSON. This PR make collaborate between Prism and Sketch Measure easier than manual color management.

### CODE REVIEW

**Comment by griffin-stewie** [comment]
@LaloMrtnz 
Could you see this Pull Request?

**Comment by griffin-stewie** [comment]
@jenniesyip @Adrxx @LaloMrtnz @Acotker 
Could you merge my PR? #37 would be solved if it merged.

**Comment by griffin-stewie** [comment]
Thank you!

**Comment by Adrxx** [comment]
Thank you @griffin-stewie ;)

**Pull request merged**
